Fix Class-Path of OpenNI.jar and com.primesense.NITE.jar
openni.rb 及び nite.rb で .jar ファイルの置き場所を

```ruby
"#{share}/java"
```

にしているため、修正前だと下記のようなエラーが発生する

```
$ java -Djava.library.path=`brew --prefix`/lib -jar org.OpenNI.Samples.UserTracker.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/OpenNI/GeneralException
	  at org.OpenNI.Samples.UserTracker.UserTrackerApplication.main(UserTrackerApplication.java:67)
Caused by: java.lang.ClassNotFoundException: org.OpenNI.GeneralException
       at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

NITE の `Sample/Bin/x64-Relase/com.primesense.NITE.Samples.Boxes.jar` は
tar.bz2 の時点で既に作成済みなので Class-Path を変えられず。
jar 展開 → MANIFEST.MF で inreplace → jar 生成しなおす、でもいいけど。